exclude: ".txt"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.2
    hooks:
      - id: ruff
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        args: [--no-semi]
        exclude: "^conf/|.*\\.html$"
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.0.0-beta.1
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint
          - eslint-config-prettier
          - "@babel/core"
          - "@babel/eslint-parser"
          - "@babel/preset-env"
